DTC_INCLUDE += $(srctree)/../sm8750-modules/qcom/opensource/synx-kernel

include $(srctree)/$(src)/config/pineapple.mk
include $(srctree)/$(src)/config/sun.mk

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
