DTC_INCLUDE += $(srctree)/../sm8750-modules/qcom/opensource/camera-kernel

include $(srctree)/$(src)/config/canoe.mk
include $(srctree)/$(src)/config/kalama.mk
include $(srctree)/$(src)/config/parrot.mk
include $(srctree)/$(src)/config/pineapple.mk
include $(srctree)/$(src)/config/pineapple_tuivm.mk
include $(srctree)/$(src)/config/sun.mk
include $(srctree)/$(src)/config/waipio.mk

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
